//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sough {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sough.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à السعر.
        /// </summary>
        public static string adPrix {
            get {
                return ResourceManager.GetString("adPrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à اتوماتيك.
        /// </summary>
        public static string automatique {
            get {
                return ResourceManager.GetString("automatique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ادخل.
        /// </summary>
        public static string btn_entree {
            get {
                return ResourceManager.GetString("btn_entree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à تم.
        /// </summary>
        public static string btn1 {
            get {
                return ResourceManager.GetString("btn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à شاهد شكل الإعلان.
        /// </summary>
        public static string btn2 {
            get {
                return ResourceManager.GetString("btn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à التصنيف.
        /// </summary>
        public static string categorie {
            get {
                return ResourceManager.GetString("categorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à valider.
        /// </summary>
        public static string CreatAdValueBtn {
            get {
                return ResourceManager.GetString("CreatAdValueBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à فقط رقم الهاتف إجباري..
        /// </summary>
        public static string create_blockquote1_footer {
            get {
                return ResourceManager.GetString("create_blockquote1_footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à بيانات التاجر..
        /// </summary>
        public static string create_blockquote1_p {
            get {
                return ResourceManager.GetString("create_blockquote1_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الصورة الرئيسية.
        /// </summary>
        public static string create_lbl_img_main {
            get {
                return ResourceManager.GetString("create_lbl_img_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à رقم الهاتف.
        /// </summary>
        public static string create_placeholder_tel {
            get {
                return ResourceManager.GetString("create_placeholder_tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à اعلاش كود ؟.
        /// </summary>
        public static string create_pourquoi {
            get {
                return ResourceManager.GetString("create_pourquoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à اسانس.
        /// </summary>
        public static string essance {
            get {
                return ResourceManager.GetString("essance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à كزوال.
        /// </summary>
        public static string gasoile {
            get {
                return ResourceManager.GetString("gasoile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à المعلومات.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à لون و شكل السيارة.
        /// </summary>
        public static string label_couleur_et_type {
            get {
                return ResourceManager.GetString("label_couleur_et_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à آخر.
        /// </summary>
        public static string LabelAutre {
            get {
                return ResourceManager.GetString("LabelAutre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ابوات فيتس.
        /// </summary>
        public static string LabelBoiteDeVitesse {
            get {
                return ResourceManager.GetString("LabelBoiteDeVitesse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à نوعية الوقود.
        /// </summary>
        public static string LabelCarburant {
            get {
                return ResourceManager.GetString("LabelCarburant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الحي.
        /// </summary>
        public static string LabelCartier {
            get {
                return ResourceManager.GetString("LabelCartier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string LabelCylindre {
            get {
                return ResourceManager.GetString("LabelCylindre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à البريد الألكتروني.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à مفروش أو غير مفروش.
        /// </summary>
        public static string LabelEstMeuble {
            get {
                return ResourceManager.GetString("LabelEstMeuble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à فيس بوك.
        /// </summary>
        public static string LabelFacebook {
            get {
                return ResourceManager.GetString("LabelFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à أنا موافق على شروط الإستخدام.
        /// </summary>
        public static string LabelIamAgree {
            get {
                return ResourceManager.GetString("LabelIamAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à اربع صور أساسيين.
        /// </summary>
        public static string LabelImageVoiture {
            get {
                return ResourceManager.GetString("LabelImageVoiture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à انستااكرام.
        /// </summary>
        public static string LabelInstagram {
            get {
                return ResourceManager.GetString("LabelInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à المسافة المقطوعة.
        /// </summary>
        public static string LabelKilometrage {
            get {
                return ResourceManager.GetString("LabelKilometrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à سعر الإيجار للشهر.
        /// </summary>
        public static string LabelLoyerMensuel {
            get {
                return ResourceManager.GetString("LabelLoyerMensuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à نوع السيارة.
        /// </summary>
        public static string LabelMarque {
            get {
                return ResourceManager.GetString("LabelMarque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à المودل.
        /// </summary>
        public static string LabelModele {
            get {
                return ResourceManager.GetString("LabelModele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à اختر كلمة مرور.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à أعد كتابة كلمة المرور.
        /// </summary>
        public static string LabelPasswordConfirme {
            get {
                return ResourceManager.GetString("LabelPasswordConfirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à رقم الهاتف.
        /// </summary>
        public static string LabelPhone {
            get {
                return ResourceManager.GetString("LabelPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à عدد الغرف.
        /// </summary>
        public static string LabelPieces {
            get {
                return ResourceManager.GetString("LabelPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à السعر.
        /// </summary>
        public static string LabelPrix {
            get {
                return ResourceManager.GetString("LabelPrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à المساحة.
        /// </summary>
        public static string LabelSurface {
            get {
                return ResourceManager.GetString("LabelSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الإسم.
        /// </summary>
        public static string LabelTraderName {
            get {
                return ResourceManager.GetString("LabelTraderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à نوع العقار.
        /// </summary>
        public static string LabelTypeDeBien {
            get {
                return ResourceManager.GetString("LabelTypeDeBien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à المدينة.
        /// </summary>
        public static string LabelVille {
            get {
                return ResourceManager.GetString("LabelVille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à المدن.
        /// </summary>
        public static string LabelVilles {
            get {
                return ResourceManager.GetString("LabelVilles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à السرعة.
        /// </summary>
        public static string LabelVitesse {
            get {
                return ResourceManager.GetString("LabelVitesse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à مانييل.
        /// </summary>
        public static string manuel {
            get {
                return ResourceManager.GetString("manuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à جديدة.
        /// </summary>
        public static string Neuf_fem {
            get {
                return ResourceManager.GetString("Neuf_fem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à جديد.
        /// </summary>
        public static string Neuf_mas {
            get {
                return ResourceManager.GetString("Neuf_mas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الإسم.
        /// </summary>
        public static string nom {
            get {
                return ResourceManager.GetString("nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à مستعملة.
        /// </summary>
        public static string Occasion_fem {
            get {
                return ResourceManager.GetString("Occasion_fem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à مستعمل.
        /// </summary>
        public static string Occasion_mas {
            get {
                return ResourceManager.GetString("Occasion_mas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à رقم الهاتف.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à xyz@example.com.
        /// </summary>
        public static string placeholder_email {
            get {
                return ResourceManager.GetString("placeholder_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à كلمة المرور.
        /// </summary>
        public static string placeholder_password {
            get {
                return ResourceManager.GetString("placeholder_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الكود ورقم الهاتف أساسيين من أجل تغيير البيانات إذا أردتم ذلك, والوصول إلى بضاعتكم..
        /// </summary>
        public static string pourquoi_pass {
            get {
                return ResourceManager.GetString("pourquoi_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à السعر.
        /// </summary>
        public static string prix {
            get {
                return ResourceManager.GetString("prix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à اختيار.
        /// </summary>
        public static string select_choisir {
            get {
                return ResourceManager.GetString("select_choisir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à لعيون.
        /// </summary>
        public static string select_ville_aioun {
            get {
                return ResourceManager.GetString("select_ville_aioun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à اكجوجت.
        /// </summary>
        public static string select_ville_akjoujt {
            get {
                return ResourceManager.GetString("select_ville_akjoujt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ألاك.
        /// </summary>
        public static string select_ville_aleg {
            get {
                return ResourceManager.GetString("select_ville_aleg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à أطار.
        /// </summary>
        public static string select_ville_atar {
            get {
                return ResourceManager.GetString("select_ville_atar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à كرو.
        /// </summary>
        public static string select_ville_guerou {
            get {
                return ResourceManager.GetString("select_ville_guerou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à كيهيدي.
        /// </summary>
        public static string select_ville_kaedi {
            get {
                return ResourceManager.GetString("select_ville_kaedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à كيفة.
        /// </summary>
        public static string select_ville_kiffa {
            get {
                return ResourceManager.GetString("select_ville_kiffa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à مقطع لحجار.
        /// </summary>
        public static string select_ville_magta_lahjar {
            get {
                return ResourceManager.GetString("select_ville_magta_lahjar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à انواذيبو.
        /// </summary>
        public static string select_ville_ndb {
            get {
                return ResourceManager.GetString("select_ville_ndb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à النعمة.
        /// </summary>
        public static string select_ville_nema {
            get {
                return ResourceManager.GetString("select_ville_nema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à انواكشوط.
        /// </summary>
        public static string select_ville_nktt {
            get {
                return ResourceManager.GetString("select_ville_nktt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à روصو.
        /// </summary>
        public static string select_ville_rosso {
            get {
                return ResourceManager.GetString("select_ville_rosso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à سيليبابي.
        /// </summary>
        public static string select_ville_selibaby {
            get {
                return ResourceManager.GetString("select_ville_selibaby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à تجكجة.
        /// </summary>
        public static string select_ville_tidjikja {
            get {
                return ResourceManager.GetString("select_ville_tidjikja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ازويرات.
        /// </summary>
        public static string select_ville_zouerate {
            get {
                return ResourceManager.GetString("select_ville_zouerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gb.
        /// </summary>
        public static string SGb {
            get {
                return ResourceManager.GetString("SGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MP.
        /// </summary>
        public static string SMP {
            get {
                return ResourceManager.GetString("SMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à جميع الفئات.
        /// </summary>
        public static string tc {
            get {
                return ResourceManager.GetString("tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à اوقية.
        /// </summary>
        public static string uguiya {
            get {
                return ResourceManager.GetString("uguiya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à واحدة أو أكثر.
        /// </summary>
        public static string UnOuPlus {
            get {
                return ResourceManager.GetString("UnOuPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à المدينة.
        /// </summary>
        public static string ville {
            get {
                return ResourceManager.GetString("ville", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ادخل اسم المدينة التي تتواجد فيها.
        /// </summary>
        public static string villeRqd {
            get {
                return ResourceManager.GetString("villeRqd", resourceCulture);
            }
        }
    }
}
