//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sough {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sough.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à السعر.
        /// </summary>
        public static string adPrix {
            get {
                return ResourceManager.GetString("adPrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à أدرار.
        /// </summary>
        public static string adrar {
            get {
                return ResourceManager.GetString("adrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à لعصابة.
        /// </summary>
        public static string assaba {
            get {
                return ResourceManager.GetString("assaba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à اتوماتيك.
        /// </summary>
        public static string automatique {
            get {
                return ResourceManager.GetString("automatique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à لبراكنة.
        /// </summary>
        public static string brakna {
            get {
                return ResourceManager.GetString("brakna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  بحث.
        /// </summary>
        public static string btn_cherche {
            get {
                return ResourceManager.GetString("btn_cherche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ادخل.
        /// </summary>
        public static string btn_entree {
            get {
                return ResourceManager.GetString("btn_entree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à انشر سلعتك.
        /// </summary>
        public static string btn_pub {
            get {
                return ResourceManager.GetString("btn_pub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à تم.
        /// </summary>
        public static string btn1 {
            get {
                return ResourceManager.GetString("btn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à شاهد شكل الإعلان.
        /// </summary>
        public static string btn2 {
            get {
                return ResourceManager.GetString("btn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à إكسسوارات.
        /// </summary>
        public static string cat_accessoires {
            get {
                return ResourceManager.GetString("cat_accessoires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الزراعة.
        /// </summary>
        public static string cat_agriculture {
            get {
                return ResourceManager.GetString("cat_agriculture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الحيوان.
        /// </summary>
        public static string cat_annimaux {
            get {
                return ResourceManager.GetString("cat_annimaux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à المظهر.
        /// </summary>
        public static string cat_apparence {
            get {
                return ResourceManager.GetString("cat_apparence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à غير مصنف عندنا.
        /// </summary>
        public static string cat_autres {
            get {
                return ResourceManager.GetString("cat_autres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الجمال والصحة.
        /// </summary>
        public static string cat_beaute_bienetre {
            get {
                return ResourceManager.GetString("cat_beaute_bienetre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الحلي و الساعات.
        /// </summary>
        public static string cat_bijoux_montres {
            get {
                return ResourceManager.GetString("cat_bijoux_montres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à كاميرات.
        /// </summary>
        public static string cat_camera {
            get {
                return ResourceManager.GetString("cat_camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الإبل.
        /// </summary>
        public static string cat_chameaux {
            get {
                return ResourceManager.GetString("cat_chameaux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الغنم.
        /// </summary>
        public static string cat_chevres_moutons {
            get {
                return ResourceManager.GetString("cat_chevres_moutons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الأجهزة المنزلية.
        /// </summary>
        public static string cat_electromenagers {
            get {
                return ResourceManager.GetString("cat_electromenagers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à التوظيف.
        /// </summary>
        public static string cat_emploi {
            get {
                return ResourceManager.GetString("cat_emploi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الوظائف والخدمات.
        /// </summary>
        public static string cat_emploi_services {
            get {
                return ResourceManager.GetString("cat_emploi_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à حوائج الأطفال.
        /// </summary>
        public static string cat_enfant_bebe {
            get {
                return ResourceManager.GetString("cat_enfant_bebe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à العقار.
        /// </summary>
        public static string cat_immobilier {
            get {
                return ResourceManager.GetString("cat_immobilier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الألعاب.
        /// </summary>
        public static string cat_jeux {
            get {
                return ResourceManager.GetString("cat_jeux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الكتب.
        /// </summary>
        public static string cat_livres {
            get {
                return ResourceManager.GetString("cat_livres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الإيجار.
        /// </summary>
        public static string cat_location {
            get {
                return ResourceManager.GetString("cat_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à المنزل.
        /// </summary>
        public static string cat_maison {
            get {
                return ResourceManager.GetString("cat_maison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الأثاث.
        /// </summary>
        public static string cat_meuble {
            get {
                return ResourceManager.GetString("cat_meuble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الميلتيميديا.
        /// </summary>
        public static string cat_multimedia {
            get {
                return ResourceManager.GetString("cat_multimedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الحواسيب المكتبية.
        /// </summary>
        public static string cat_ordinateurs_bureau {
            get {
                return ResourceManager.GetString("cat_ordinateurs_bureau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الحواسيب المحمولة.
        /// </summary>
        public static string cat_ordinateurs_portables {
            get {
                return ResourceManager.GetString("cat_ordinateurs_portables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à العطور.
        /// </summary>
        public static string cat_parfums {
            get {
                return ResourceManager.GetString("cat_parfums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à قطع الغيار.
        /// </summary>
        public static string cat_pieces_detachees {
            get {
                return ResourceManager.GetString("cat_pieces_detachees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à السيرفيرات.
        /// </summary>
        public static string cat_serveurs {
            get {
                return ResourceManager.GetString("cat_serveurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الخدمات.
        /// </summary>
        public static string cat_services {
            get {
                return ResourceManager.GetString("cat_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à مسائل الرياضة.
        /// </summary>
        public static string cat_sports {
            get {
                return ResourceManager.GetString("cat_sports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à التابليت.
        /// </summary>
        public static string cat_tablette {
            get {
                return ResourceManager.GetString("cat_tablette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الهواتف.
        /// </summary>
        public static string cat_telephones {
            get {
                return ResourceManager.GetString("cat_telephones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à التيلفيزيون.
        /// </summary>
        public static string cat_televisions {
            get {
                return ResourceManager.GetString("cat_televisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الأواني.
        /// </summary>
        public static string cat_ustensiles {
            get {
                return ResourceManager.GetString("cat_ustensiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à البقر.
        /// </summary>
        public static string cat_vaches {
            get {
                return ResourceManager.GetString("cat_vaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à المركبات.
        /// </summary>
        public static string cat_vehicules {
            get {
                return ResourceManager.GetString("cat_vehicules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à مبيعات العقارات.
        /// </summary>
        public static string cat_vente_immobilier {
            get {
                return ResourceManager.GetString("cat_vente_immobilier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الملابس.
        /// </summary>
        public static string cat_Vetements {
            get {
                return ResourceManager.GetString("cat_Vetements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à السيارات.
        /// </summary>
        public static string cat_voiture {
            get {
                return ResourceManager.GetString("cat_voiture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à تم.
        /// </summary>
        public static string CreatAdValueBtn {
            get {
                return ResourceManager.GetString("CreatAdValueBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à فقط رقم الهاتف إجباري..
        /// </summary>
        public static string create_blockquote1_footer {
            get {
                return ResourceManager.GetString("create_blockquote1_footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à بيانات التاجر..
        /// </summary>
        public static string create_blockquote1_p {
            get {
                return ResourceManager.GetString("create_blockquote1_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الصورة الرئيسية.
        /// </summary>
        public static string create_lbl_img_main {
            get {
                return ResourceManager.GetString("create_lbl_img_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à رقم الهاتف.
        /// </summary>
        public static string create_placeholder_tel {
            get {
                return ResourceManager.GetString("create_placeholder_tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à اعلاش كود ؟.
        /// </summary>
        public static string create_pourquoi {
            get {
                return ResourceManager.GetString("create_pourquoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à داخلة انواذيبوا.
        /// </summary>
        public static string dakhlet_nouadhibou {
            get {
                return ResourceManager.GetString("dakhlet_nouadhibou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à البيانا ناقصة أو خاطئة.
        /// </summary>
        public static string Erreur_data {
            get {
                return ResourceManager.GetString("Erreur_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à كلمة المرور غير صحيحة.
        /// </summary>
        public static string Erreur_password {
            get {
                return ResourceManager.GetString("Erreur_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à اسانس.
        /// </summary>
        public static string essance {
            get {
                return ResourceManager.GetString("essance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à القوانين العامة.
        /// </summary>
        public static string footer_condition_gene {
            get {
                return ResourceManager.GetString("footer_condition_gene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à اشعار قانوني.
        /// </summary>
        public static string footer_mention_legal {
            get {
                return ResourceManager.GetString("footer_mention_legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à شركائنا.
        /// </summary>
        public static string footer_partenaires {
            get {
                return ResourceManager.GetString("footer_partenaires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à كزوال.
        /// </summary>
        public static string gasoile {
            get {
                return ResourceManager.GetString("gasoile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à كوركول.
        /// </summary>
        public static string gorgol {
            get {
                return ResourceManager.GetString("gorgol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à كيديماغا.
        /// </summary>
        public static string guidimaka {
            get {
                return ResourceManager.GetString("guidimaka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الحوض الشرقي.
        /// </summary>
        public static string hodh_chargui {
            get {
                return ResourceManager.GetString("hodh_chargui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الحوض الغربي.
        /// </summary>
        public static string hodh_gharbi {
            get {
                return ResourceManager.GetString("hodh_gharbi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à انشيري.
        /// </summary>
        public static string inchiri {
            get {
                return ResourceManager.GetString("inchiri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الفئات.
        /// </summary>
        public static string index_select_categorie {
            get {
                return ResourceManager.GetString("index_select_categorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à المعلومات.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à لون و شكل السيارة.
        /// </summary>
        public static string label_couleur_et_type {
            get {
                return ResourceManager.GetString("label_couleur_et_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à جميع الفئات.
        /// </summary>
        public static string label_toute_les_cat {
            get {
                return ResourceManager.GetString("label_toute_les_cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à آخر.
        /// </summary>
        public static string LabelAutre {
            get {
                return ResourceManager.GetString("LabelAutre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ابوات فيتس.
        /// </summary>
        public static string LabelBoiteDeVitesse {
            get {
                return ResourceManager.GetString("LabelBoiteDeVitesse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à نوعية الوقود.
        /// </summary>
        public static string LabelCarburant {
            get {
                return ResourceManager.GetString("LabelCarburant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الحي.
        /// </summary>
        public static string LabelCartier {
            get {
                return ResourceManager.GetString("LabelCartier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string LabelCylindre {
            get {
                return ResourceManager.GetString("LabelCylindre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à البريد الألكتروني.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à مفروش أو غير مفروش.
        /// </summary>
        public static string LabelEstMeuble {
            get {
                return ResourceManager.GetString("LabelEstMeuble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à فيس بوك.
        /// </summary>
        public static string LabelFacebook {
            get {
                return ResourceManager.GetString("LabelFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à أنا موافق على شروط الإستخدام.
        /// </summary>
        public static string LabelIamAgree {
            get {
                return ResourceManager.GetString("LabelIamAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à اربع صور أساسيين.
        /// </summary>
        public static string LabelImageVoiture {
            get {
                return ResourceManager.GetString("LabelImageVoiture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à انستااكرام.
        /// </summary>
        public static string LabelInstagram {
            get {
                return ResourceManager.GetString("LabelInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à المسافة المقطوعة.
        /// </summary>
        public static string LabelKilometrage {
            get {
                return ResourceManager.GetString("LabelKilometrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à سعر الإيجار للشهر.
        /// </summary>
        public static string LabelLoyerMensuel {
            get {
                return ResourceManager.GetString("LabelLoyerMensuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à نوع السيارة.
        /// </summary>
        public static string LabelMarque {
            get {
                return ResourceManager.GetString("LabelMarque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à المودل.
        /// </summary>
        public static string LabelModele {
            get {
                return ResourceManager.GetString("LabelModele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à اختر كلمة مرور.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à أعد كتابة كلمة المرور.
        /// </summary>
        public static string LabelPasswordConfirme {
            get {
                return ResourceManager.GetString("LabelPasswordConfirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à رقم الهاتف.
        /// </summary>
        public static string LabelPhone {
            get {
                return ResourceManager.GetString("LabelPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à عدد الغرف.
        /// </summary>
        public static string LabelPieces {
            get {
                return ResourceManager.GetString("LabelPieces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à السعر.
        /// </summary>
        public static string LabelPrix {
            get {
                return ResourceManager.GetString("LabelPrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à المساحة.
        /// </summary>
        public static string LabelSurface {
            get {
                return ResourceManager.GetString("LabelSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الإسم.
        /// </summary>
        public static string LabelTraderName {
            get {
                return ResourceManager.GetString("LabelTraderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à نوع العقار.
        /// </summary>
        public static string LabelTypeDeBien {
            get {
                return ResourceManager.GetString("LabelTypeDeBien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à المدينة.
        /// </summary>
        public static string LabelVille {
            get {
                return ResourceManager.GetString("LabelVille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à المدن.
        /// </summary>
        public static string LabelVilles {
            get {
                return ResourceManager.GetString("LabelVilles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à السرعة.
        /// </summary>
        public static string LabelVitesse {
            get {
                return ResourceManager.GetString("LabelVitesse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à تجار.
        /// </summary>
        public static string logo {
            get {
                return ResourceManager.GetString("logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à مانييل.
        /// </summary>
        public static string manuel {
            get {
                return ResourceManager.GetString("manuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à جديد (ة).
        /// </summary>
        public static string Neuf {
            get {
                return ResourceManager.GetString("Neuf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à جديدة.
        /// </summary>
        public static string Neuf_fem {
            get {
                return ResourceManager.GetString("Neuf_fem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à جديد.
        /// </summary>
        public static string Neuf_mas {
            get {
                return ResourceManager.GetString("Neuf_mas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الإسم.
        /// </summary>
        public static string nom {
            get {
                return ResourceManager.GetString("nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à مستعمل(ة).
        /// </summary>
        public static string Occasion {
            get {
                return ResourceManager.GetString("Occasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à مستعملة.
        /// </summary>
        public static string Occasion_fem {
            get {
                return ResourceManager.GetString("Occasion_fem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à مستعمل.
        /// </summary>
        public static string Occasion_mas {
            get {
                return ResourceManager.GetString("Occasion_mas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à خطأ! العملية غير محددة..
        /// </summary>
        public static string operation_unknown {
            get {
                return ResourceManager.GetString("operation_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à رقم الهاتف.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à xyz@example.com.
        /// </summary>
        public static string placeholder_email {
            get {
                return ResourceManager.GetString("placeholder_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à كلمة المرور.
        /// </summary>
        public static string placeholder_password {
            get {
                return ResourceManager.GetString("placeholder_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الكود ورقم الهاتف أساسيين من أجل تغيير البيانات إذا أردتم ذلك, والوصول إلى بضاعتكم..
        /// </summary>
        public static string pourquoi_pass {
            get {
                return ResourceManager.GetString("pourquoi_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à السعر.
        /// </summary>
        public static string prix {
            get {
                return ResourceManager.GetString("prix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à اختيار.
        /// </summary>
        public static string select_choisir {
            get {
                return ResourceManager.GetString("select_choisir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à لعيون.
        /// </summary>
        public static string select_ville_aioun {
            get {
                return ResourceManager.GetString("select_ville_aioun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à اكجوجت.
        /// </summary>
        public static string select_ville_akjoujt {
            get {
                return ResourceManager.GetString("select_ville_akjoujt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ألاك.
        /// </summary>
        public static string select_ville_aleg {
            get {
                return ResourceManager.GetString("select_ville_aleg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à أطار.
        /// </summary>
        public static string select_ville_atar {
            get {
                return ResourceManager.GetString("select_ville_atar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à كرو.
        /// </summary>
        public static string select_ville_guerou {
            get {
                return ResourceManager.GetString("select_ville_guerou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à كيهيدي.
        /// </summary>
        public static string select_ville_kaedi {
            get {
                return ResourceManager.GetString("select_ville_kaedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à كيفة.
        /// </summary>
        public static string select_ville_kiffa {
            get {
                return ResourceManager.GetString("select_ville_kiffa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à مقطع لحجار.
        /// </summary>
        public static string select_ville_magta_lahjar {
            get {
                return ResourceManager.GetString("select_ville_magta_lahjar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à انواذيبو.
        /// </summary>
        public static string select_ville_ndb {
            get {
                return ResourceManager.GetString("select_ville_ndb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à النعمة.
        /// </summary>
        public static string select_ville_nema {
            get {
                return ResourceManager.GetString("select_ville_nema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à انواكشوط.
        /// </summary>
        public static string select_ville_nktt {
            get {
                return ResourceManager.GetString("select_ville_nktt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à روصو.
        /// </summary>
        public static string select_ville_rosso {
            get {
                return ResourceManager.GetString("select_ville_rosso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à سيليبابي.
        /// </summary>
        public static string select_ville_selibaby {
            get {
                return ResourceManager.GetString("select_ville_selibaby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à تجكجة.
        /// </summary>
        public static string select_ville_tidjikja {
            get {
                return ResourceManager.GetString("select_ville_tidjikja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ازويرات.
        /// </summary>
        public static string select_ville_zouerate {
            get {
                return ResourceManager.GetString("select_ville_zouerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gb.
        /// </summary>
        public static string SGb {
            get {
                return ResourceManager.GetString("SGb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MP.
        /// </summary>
        public static string SMP {
            get {
                return ResourceManager.GetString("SMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à تكانت.
        /// </summary>
        public static string tagant {
            get {
                return ResourceManager.GetString("tagant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à جميع الفئات.
        /// </summary>
        public static string tc {
            get {
                return ResourceManager.GetString("tc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à تيرس زمور.
        /// </summary>
        public static string tiris {
            get {
                return ResourceManager.GetString("tiris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à الأكثر تداول.
        /// </summary>
        public static string top_cat {
            get {
                return ResourceManager.GetString("top_cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à كامل موريتانيا.
        /// </summary>
        public static string toute_les_villes {
            get {
                return ResourceManager.GetString("toute_les_villes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à اترارزة.
        /// </summary>
        public static string trarza {
            get {
                return ResourceManager.GetString("trarza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à اوقية.
        /// </summary>
        public static string uguiya {
            get {
                return ResourceManager.GetString("uguiya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à واحدة أو أكثر.
        /// </summary>
        public static string UnOuPlus {
            get {
                return ResourceManager.GetString("UnOuPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à المدينة.
        /// </summary>
        public static string ville {
            get {
                return ResourceManager.GetString("ville", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ادخل اسم المدينة التي تتواجد فيها.
        /// </summary>
        public static string villeRqd {
            get {
                return ResourceManager.GetString("villeRqd", resourceCulture);
            }
        }
    }
}
