// <auto-generated />
namespace Sough.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class firstmig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstmig));
        
        string IMigrationMetadata.Id
        {
            get { return "201703271635513_first-mig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
